/*
   Copyright 2021 The Silkworm Authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
#ifndef SILKWORM_HEADER_DOWNLOADER_HPP
#define SILKWORM_HEADER_DOWNLOADER_HPP

#include <atomic>

#include <silkworm/chain/identity.hpp>
#include <silkworm/downloader/internals/db_tx.hpp>
#include <silkworm/downloader/internals/types.hpp>
#include <silkworm/downloader/messages/internal_message.hpp>

#include "stage.h"
#include "block_downloader.hpp"

namespace silkworm {

/*
 * HeaderStage implement the header downloading stage.
 * Like the other stages it has two methods, one to go forward and one to go backwards (unwind) in the chain.
 * It is the counterpart of Erigon's HeaderForward and HeadersUnwind.
 *
 * HeaderStage internally uses HeaderChain and HeaderPersistence. The first represent the growing chain in memory
 * the second represent the growing chain on db. When headers are ready to be persisted they are withdrawn from
 * HeaderChain and transferred to the HeaderPersistence that write them on the db.
 *
 * HeaderStage has:
 *    - an execution loop
 *    - a forward/unwind method pair
 *
 *  The execution loop process messages that arrives in a concurrent queue. They are of 2 types:
 *    - inbound messages (from peers), like headers announcements (that we receive), responses for our header requests
 *    - outbound messages (to peers), like headers announcements (that we propagate), header requests
 *  Each message is class that encode in the execute() method the logic to process the message itself (command pattern).
 *  Those messages operate on the HeaderChain (asking needed headers or providing arrived headers) and use the sentry.
 *  Inbound messages are generated by the sentry, outbound messages are generated by the forward/unwind methods.
 *
 *  The forward method periodically
 *     - generate some outbound messages that ask HeaderChain to generate headers request,
 *     - check if HeaderChain has headers ready to be persisted
 *     - if there are some it uses HeaderPersistence to persist them
 *     - check if HeaderPersistence has detected an unwind point
 *     - check the conditions that determines the forward method to exit (unwind detected, chain in sync)
 *  The unwind method do headers unwind down to an unwind point.
 *
 *  Since the execution loop runs in its thread and the forward/unwind methods runs in the stage loop thread a
 *  synchronisation is needed. So the HeaderStage is partitioned in 2 half: one half runs the execution loop, the
 *  other half runs the forward/unwind methods; the two half communicate only by a MessageQueue that is a thread safe
 *  queue. Thus, HeaderChain is used only in the first half and not need lock protection, whereas HeaderPersistence is
 *  used in the other thread and also do not need lock protection.
 *
 */
class HeaderStage : public Stage {
  public:
    HeaderStage(const Db::ReadWriteAccess&, BlockDownloader&);
    HeaderStage(const HeaderStage&) = delete;  // not copyable
    HeaderStage(HeaderStage&&) = delete;       // nor movable
    ~HeaderStage();

    Stage::Result forward(bool first_sync) override;  // go forward, downloading headers
    Stage::Result unwind_to(BlockNum new_height,
                            Hash bad_block) override;  // go backward, unwinding headers to new_height

  private:
    void send_header_requests();  // send requests for more headers
    void send_announcements();
    auto sync_header_chain(BlockNum highest_in_db) -> std::shared_ptr<InternalMessage<void>>;
    auto withdraw_stable_headers() -> std::shared_ptr<InternalMessage<std::tuple<Headers, bool>>>;
    auto update_bad_headers(std::set<Hash>) -> std::shared_ptr<InternalMessage<void>>;
    void receive_message(const sentry::InboundMessage&);

    Db::ReadWriteAccess db_access_;
    BlockDownloader& block_downloader_;
};

}  // namespace silkworm

#endif  // SILKWORM_HEADER_DOWNLOADER_HPP
