// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote/bor.proto

#include "remote/bor.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace remote {
PROTOBUF_CONSTEXPR BorTxnLookupRequest::BorTxnLookupRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bor_tx_hash_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BorTxnLookupRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BorTxnLookupRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BorTxnLookupRequestDefaultTypeInternal() {}
  union {
    BorTxnLookupRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BorTxnLookupRequestDefaultTypeInternal _BorTxnLookupRequest_default_instance_;
PROTOBUF_CONSTEXPR BorTxnLookupReply::BorTxnLookupReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_number_)*/uint64_t{0u}
  , /*decltype(_impl_.present_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BorTxnLookupReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BorTxnLookupReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BorTxnLookupReplyDefaultTypeInternal() {}
  union {
    BorTxnLookupReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BorTxnLookupReplyDefaultTypeInternal _BorTxnLookupReply_default_instance_;
PROTOBUF_CONSTEXPR BorEventsRequest::BorEventsRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_hash_)*/nullptr
  , /*decltype(_impl_.block_num_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BorEventsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BorEventsRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BorEventsRequestDefaultTypeInternal() {}
  union {
    BorEventsRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BorEventsRequestDefaultTypeInternal _BorEventsRequest_default_instance_;
PROTOBUF_CONSTEXPR BorEventsReply::BorEventsReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.event_rlps_)*/{}
  , /*decltype(_impl_.state_receiver_contract_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BorEventsReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BorEventsReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BorEventsReplyDefaultTypeInternal() {}
  union {
    BorEventsReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BorEventsReplyDefaultTypeInternal _BorEventsReply_default_instance_;
PROTOBUF_CONSTEXPR BorProducersRequest::BorProducersRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_num_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BorProducersRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BorProducersRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BorProducersRequestDefaultTypeInternal() {}
  union {
    BorProducersRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BorProducersRequestDefaultTypeInternal _BorProducersRequest_default_instance_;
PROTOBUF_CONSTEXPR BorProducersResponse::BorProducersResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.validators_)*/{}
  , /*decltype(_impl_.proposer_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BorProducersResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BorProducersResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BorProducersResponseDefaultTypeInternal() {}
  union {
    BorProducersResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BorProducersResponseDefaultTypeInternal _BorProducersResponse_default_instance_;
PROTOBUF_CONSTEXPR Validator::Validator(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.address_)*/nullptr
  , /*decltype(_impl_.id_)*/uint64_t{0u}
  , /*decltype(_impl_.voting_power_)*/int64_t{0}
  , /*decltype(_impl_.proposer_priority_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ValidatorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ValidatorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ValidatorDefaultTypeInternal() {}
  union {
    Validator _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ValidatorDefaultTypeInternal _Validator_default_instance_;
}  // namespace remote
static ::_pb::Metadata file_level_metadata_remote_2fbor_2eproto[7];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_remote_2fbor_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_remote_2fbor_2eproto = nullptr;

const uint32_t TableStruct_remote_2fbor_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::BorTxnLookupRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::BorTxnLookupRequest, _impl_.bor_tx_hash_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::BorTxnLookupReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::BorTxnLookupReply, _impl_.present_),
  PROTOBUF_FIELD_OFFSET(::remote::BorTxnLookupReply, _impl_.block_number_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::BorEventsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::BorEventsRequest, _impl_.block_num_),
  PROTOBUF_FIELD_OFFSET(::remote::BorEventsRequest, _impl_.block_hash_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::BorEventsReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::BorEventsReply, _impl_.state_receiver_contract_address_),
  PROTOBUF_FIELD_OFFSET(::remote::BorEventsReply, _impl_.event_rlps_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::BorProducersRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::BorProducersRequest, _impl_.block_num_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::BorProducersResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::BorProducersResponse, _impl_.proposer_),
  PROTOBUF_FIELD_OFFSET(::remote::BorProducersResponse, _impl_.validators_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::Validator, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::Validator, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::remote::Validator, _impl_.address_),
  PROTOBUF_FIELD_OFFSET(::remote::Validator, _impl_.voting_power_),
  PROTOBUF_FIELD_OFFSET(::remote::Validator, _impl_.proposer_priority_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::remote::BorTxnLookupRequest)},
  { 7, -1, -1, sizeof(::remote::BorTxnLookupReply)},
  { 15, -1, -1, sizeof(::remote::BorEventsRequest)},
  { 23, -1, -1, sizeof(::remote::BorEventsReply)},
  { 31, -1, -1, sizeof(::remote::BorProducersRequest)},
  { 38, -1, -1, sizeof(::remote::BorProducersResponse)},
  { 46, -1, -1, sizeof(::remote::Validator)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::remote::_BorTxnLookupRequest_default_instance_._instance,
  &::remote::_BorTxnLookupReply_default_instance_._instance,
  &::remote::_BorEventsRequest_default_instance_._instance,
  &::remote::_BorEventsReply_default_instance_._instance,
  &::remote::_BorProducersRequest_default_instance_._instance,
  &::remote::_BorProducersResponse_default_instance_._instance,
  &::remote::_Validator_default_instance_._instance,
};

const char descriptor_table_protodef_remote_2fbor_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020remote/bor.proto\022\006remote\032\033google/proto"
  "buf/empty.proto\032\021types/types.proto\"7\n\023Bo"
  "rTxnLookupRequest\022 \n\013bor_tx_hash\030\001 \001(\0132\013"
  ".types.H256\":\n\021BorTxnLookupReply\022\017\n\007pres"
  "ent\030\001 \001(\010\022\024\n\014block_number\030\002 \001(\004\"F\n\020BorEv"
  "entsRequest\022\021\n\tblock_num\030\001 \001(\004\022\037\n\nblock_"
  "hash\030\002 \001(\0132\013.types.H256\"M\n\016BorEventsRepl"
  "y\022\'\n\037state_receiver_contract_address\030\001 \001"
  "(\t\022\022\n\nevent_rlps\030\002 \003(\014\"(\n\023BorProducersRe"
  "quest\022\021\n\tblock_num\030\001 \001(\004\"b\n\024BorProducers"
  "Response\022#\n\010proposer\030\001 \001(\0132\021.remote.Vali"
  "dator\022%\n\nvalidators\030\002 \003(\0132\021.remote.Valid"
  "ator\"f\n\tValidator\022\n\n\002id\030\001 \001(\004\022\034\n\007address"
  "\030\002 \001(\0132\013.types.H160\022\024\n\014voting_power\030\003 \001("
  "\003\022\031\n\021proposer_priority\030\004 \001(\0032\316\001\n\rBridgeB"
  "ackend\0226\n\007Version\022\026.google.protobuf.Empt"
  "y\032\023.types.VersionReply\022F\n\014BorTxnLookup\022\033"
  ".remote.BorTxnLookupRequest\032\031.remote.Bor"
  "TxnLookupReply\022=\n\tBorEvents\022\030.remote.Bor"
  "EventsRequest\032\026.remote.BorEventsReply2\221\001"
  "\n\017HeimdallBackend\0226\n\007Version\022\026.google.pr"
  "otobuf.Empty\032\023.types.VersionReply\022F\n\tPro"
  "ducers\022\033.remote.BorProducersRequest\032\034.re"
  "mote.BorProducersResponseB\026Z\024./remote;re"
  "moteprotob\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_remote_2fbor_2eproto_deps[2] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_types_2ftypes_2eproto,
};
static ::_pbi::once_flag descriptor_table_remote_2fbor_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_remote_2fbor_2eproto = {
    false, false, 977, descriptor_table_protodef_remote_2fbor_2eproto,
    "remote/bor.proto",
    &descriptor_table_remote_2fbor_2eproto_once, descriptor_table_remote_2fbor_2eproto_deps, 2, 7,
    schemas, file_default_instances, TableStruct_remote_2fbor_2eproto::offsets,
    file_level_metadata_remote_2fbor_2eproto, file_level_enum_descriptors_remote_2fbor_2eproto,
    file_level_service_descriptors_remote_2fbor_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_remote_2fbor_2eproto_getter() {
  return &descriptor_table_remote_2fbor_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_remote_2fbor_2eproto(&descriptor_table_remote_2fbor_2eproto);
namespace remote {

// ===================================================================

class BorTxnLookupRequest::_Internal {
 public:
  static const ::types::H256& bor_tx_hash(const BorTxnLookupRequest* msg);
};

const ::types::H256&
BorTxnLookupRequest::_Internal::bor_tx_hash(const BorTxnLookupRequest* msg) {
  return *msg->_impl_.bor_tx_hash_;
}
void BorTxnLookupRequest::clear_bor_tx_hash() {
  if (GetArenaForAllocation() == nullptr && _impl_.bor_tx_hash_ != nullptr) {
    delete _impl_.bor_tx_hash_;
  }
  _impl_.bor_tx_hash_ = nullptr;
}
BorTxnLookupRequest::BorTxnLookupRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.BorTxnLookupRequest)
}
BorTxnLookupRequest::BorTxnLookupRequest(const BorTxnLookupRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BorTxnLookupRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bor_tx_hash_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_bor_tx_hash()) {
    _this->_impl_.bor_tx_hash_ = new ::types::H256(*from._impl_.bor_tx_hash_);
  }
  // @@protoc_insertion_point(copy_constructor:remote.BorTxnLookupRequest)
}

inline void BorTxnLookupRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bor_tx_hash_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BorTxnLookupRequest::~BorTxnLookupRequest() {
  // @@protoc_insertion_point(destructor:remote.BorTxnLookupRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BorTxnLookupRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.bor_tx_hash_;
}

void BorTxnLookupRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BorTxnLookupRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.BorTxnLookupRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.bor_tx_hash_ != nullptr) {
    delete _impl_.bor_tx_hash_;
  }
  _impl_.bor_tx_hash_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BorTxnLookupRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .types.H256 bor_tx_hash = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_bor_tx_hash(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BorTxnLookupRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.BorTxnLookupRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .types.H256 bor_tx_hash = 1;
  if (this->_internal_has_bor_tx_hash()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::bor_tx_hash(this),
        _Internal::bor_tx_hash(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.BorTxnLookupRequest)
  return target;
}

size_t BorTxnLookupRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.BorTxnLookupRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .types.H256 bor_tx_hash = 1;
  if (this->_internal_has_bor_tx_hash()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.bor_tx_hash_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BorTxnLookupRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BorTxnLookupRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BorTxnLookupRequest::GetClassData() const { return &_class_data_; }


void BorTxnLookupRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BorTxnLookupRequest*>(&to_msg);
  auto& from = static_cast<const BorTxnLookupRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.BorTxnLookupRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_bor_tx_hash()) {
    _this->_internal_mutable_bor_tx_hash()->::types::H256::MergeFrom(
        from._internal_bor_tx_hash());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BorTxnLookupRequest::CopyFrom(const BorTxnLookupRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.BorTxnLookupRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BorTxnLookupRequest::IsInitialized() const {
  return true;
}

void BorTxnLookupRequest::InternalSwap(BorTxnLookupRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.bor_tx_hash_, other->_impl_.bor_tx_hash_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BorTxnLookupRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_remote_2fbor_2eproto_getter, &descriptor_table_remote_2fbor_2eproto_once,
      file_level_metadata_remote_2fbor_2eproto[0]);
}

// ===================================================================

class BorTxnLookupReply::_Internal {
 public:
};

BorTxnLookupReply::BorTxnLookupReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.BorTxnLookupReply)
}
BorTxnLookupReply::BorTxnLookupReply(const BorTxnLookupReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BorTxnLookupReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_number_){}
    , decltype(_impl_.present_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.block_number_, &from._impl_.block_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.present_) -
    reinterpret_cast<char*>(&_impl_.block_number_)) + sizeof(_impl_.present_));
  // @@protoc_insertion_point(copy_constructor:remote.BorTxnLookupReply)
}

inline void BorTxnLookupReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_number_){uint64_t{0u}}
    , decltype(_impl_.present_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BorTxnLookupReply::~BorTxnLookupReply() {
  // @@protoc_insertion_point(destructor:remote.BorTxnLookupReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BorTxnLookupReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BorTxnLookupReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BorTxnLookupReply::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.BorTxnLookupReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.block_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.present_) -
      reinterpret_cast<char*>(&_impl_.block_number_)) + sizeof(_impl_.present_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BorTxnLookupReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool present = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.present_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 block_number = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.block_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BorTxnLookupReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.BorTxnLookupReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool present = 1;
  if (this->_internal_present() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_present(), target);
  }

  // uint64 block_number = 2;
  if (this->_internal_block_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_block_number(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.BorTxnLookupReply)
  return target;
}

size_t BorTxnLookupReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.BorTxnLookupReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 block_number = 2;
  if (this->_internal_block_number() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_block_number());
  }

  // bool present = 1;
  if (this->_internal_present() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BorTxnLookupReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BorTxnLookupReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BorTxnLookupReply::GetClassData() const { return &_class_data_; }


void BorTxnLookupReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BorTxnLookupReply*>(&to_msg);
  auto& from = static_cast<const BorTxnLookupReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.BorTxnLookupReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_block_number() != 0) {
    _this->_internal_set_block_number(from._internal_block_number());
  }
  if (from._internal_present() != 0) {
    _this->_internal_set_present(from._internal_present());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BorTxnLookupReply::CopyFrom(const BorTxnLookupReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.BorTxnLookupReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BorTxnLookupReply::IsInitialized() const {
  return true;
}

void BorTxnLookupReply::InternalSwap(BorTxnLookupReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BorTxnLookupReply, _impl_.present_)
      + sizeof(BorTxnLookupReply::_impl_.present_)
      - PROTOBUF_FIELD_OFFSET(BorTxnLookupReply, _impl_.block_number_)>(
          reinterpret_cast<char*>(&_impl_.block_number_),
          reinterpret_cast<char*>(&other->_impl_.block_number_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BorTxnLookupReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_remote_2fbor_2eproto_getter, &descriptor_table_remote_2fbor_2eproto_once,
      file_level_metadata_remote_2fbor_2eproto[1]);
}

// ===================================================================

class BorEventsRequest::_Internal {
 public:
  static const ::types::H256& block_hash(const BorEventsRequest* msg);
};

const ::types::H256&
BorEventsRequest::_Internal::block_hash(const BorEventsRequest* msg) {
  return *msg->_impl_.block_hash_;
}
void BorEventsRequest::clear_block_hash() {
  if (GetArenaForAllocation() == nullptr && _impl_.block_hash_ != nullptr) {
    delete _impl_.block_hash_;
  }
  _impl_.block_hash_ = nullptr;
}
BorEventsRequest::BorEventsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.BorEventsRequest)
}
BorEventsRequest::BorEventsRequest(const BorEventsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BorEventsRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_hash_){nullptr}
    , decltype(_impl_.block_num_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_block_hash()) {
    _this->_impl_.block_hash_ = new ::types::H256(*from._impl_.block_hash_);
  }
  _this->_impl_.block_num_ = from._impl_.block_num_;
  // @@protoc_insertion_point(copy_constructor:remote.BorEventsRequest)
}

inline void BorEventsRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_hash_){nullptr}
    , decltype(_impl_.block_num_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BorEventsRequest::~BorEventsRequest() {
  // @@protoc_insertion_point(destructor:remote.BorEventsRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BorEventsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.block_hash_;
}

void BorEventsRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BorEventsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.BorEventsRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.block_hash_ != nullptr) {
    delete _impl_.block_hash_;
  }
  _impl_.block_hash_ = nullptr;
  _impl_.block_num_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BorEventsRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 block_num = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.block_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .types.H256 block_hash = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_block_hash(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BorEventsRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.BorEventsRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 block_num = 1;
  if (this->_internal_block_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_block_num(), target);
  }

  // .types.H256 block_hash = 2;
  if (this->_internal_has_block_hash()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::block_hash(this),
        _Internal::block_hash(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.BorEventsRequest)
  return target;
}

size_t BorEventsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.BorEventsRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .types.H256 block_hash = 2;
  if (this->_internal_has_block_hash()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.block_hash_);
  }

  // uint64 block_num = 1;
  if (this->_internal_block_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_block_num());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BorEventsRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BorEventsRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BorEventsRequest::GetClassData() const { return &_class_data_; }


void BorEventsRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BorEventsRequest*>(&to_msg);
  auto& from = static_cast<const BorEventsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.BorEventsRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_block_hash()) {
    _this->_internal_mutable_block_hash()->::types::H256::MergeFrom(
        from._internal_block_hash());
  }
  if (from._internal_block_num() != 0) {
    _this->_internal_set_block_num(from._internal_block_num());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BorEventsRequest::CopyFrom(const BorEventsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.BorEventsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BorEventsRequest::IsInitialized() const {
  return true;
}

void BorEventsRequest::InternalSwap(BorEventsRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BorEventsRequest, _impl_.block_num_)
      + sizeof(BorEventsRequest::_impl_.block_num_)
      - PROTOBUF_FIELD_OFFSET(BorEventsRequest, _impl_.block_hash_)>(
          reinterpret_cast<char*>(&_impl_.block_hash_),
          reinterpret_cast<char*>(&other->_impl_.block_hash_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BorEventsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_remote_2fbor_2eproto_getter, &descriptor_table_remote_2fbor_2eproto_once,
      file_level_metadata_remote_2fbor_2eproto[2]);
}

// ===================================================================

class BorEventsReply::_Internal {
 public:
};

BorEventsReply::BorEventsReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.BorEventsReply)
}
BorEventsReply::BorEventsReply(const BorEventsReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BorEventsReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.event_rlps_){from._impl_.event_rlps_}
    , decltype(_impl_.state_receiver_contract_address_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.state_receiver_contract_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.state_receiver_contract_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_state_receiver_contract_address().empty()) {
    _this->_impl_.state_receiver_contract_address_.Set(from._internal_state_receiver_contract_address(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:remote.BorEventsReply)
}

inline void BorEventsReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.event_rlps_){arena}
    , decltype(_impl_.state_receiver_contract_address_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.state_receiver_contract_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.state_receiver_contract_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BorEventsReply::~BorEventsReply() {
  // @@protoc_insertion_point(destructor:remote.BorEventsReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BorEventsReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.event_rlps_.~RepeatedPtrField();
  _impl_.state_receiver_contract_address_.Destroy();
}

void BorEventsReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BorEventsReply::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.BorEventsReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.event_rlps_.Clear();
  _impl_.state_receiver_contract_address_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BorEventsReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string state_receiver_contract_address = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_state_receiver_contract_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "remote.BorEventsReply.state_receiver_contract_address"));
        } else
          goto handle_unusual;
        continue;
      // repeated bytes event_rlps = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_event_rlps();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BorEventsReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.BorEventsReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string state_receiver_contract_address = 1;
  if (!this->_internal_state_receiver_contract_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_state_receiver_contract_address().data(), static_cast<int>(this->_internal_state_receiver_contract_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "remote.BorEventsReply.state_receiver_contract_address");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_state_receiver_contract_address(), target);
  }

  // repeated bytes event_rlps = 2;
  for (int i = 0, n = this->_internal_event_rlps_size(); i < n; i++) {
    const auto& s = this->_internal_event_rlps(i);
    target = stream->WriteBytes(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.BorEventsReply)
  return target;
}

size_t BorEventsReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.BorEventsReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bytes event_rlps = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.event_rlps_.size());
  for (int i = 0, n = _impl_.event_rlps_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      _impl_.event_rlps_.Get(i));
  }

  // string state_receiver_contract_address = 1;
  if (!this->_internal_state_receiver_contract_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_state_receiver_contract_address());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BorEventsReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BorEventsReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BorEventsReply::GetClassData() const { return &_class_data_; }


void BorEventsReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BorEventsReply*>(&to_msg);
  auto& from = static_cast<const BorEventsReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.BorEventsReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.event_rlps_.MergeFrom(from._impl_.event_rlps_);
  if (!from._internal_state_receiver_contract_address().empty()) {
    _this->_internal_set_state_receiver_contract_address(from._internal_state_receiver_contract_address());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BorEventsReply::CopyFrom(const BorEventsReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.BorEventsReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BorEventsReply::IsInitialized() const {
  return true;
}

void BorEventsReply::InternalSwap(BorEventsReply* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.event_rlps_.InternalSwap(&other->_impl_.event_rlps_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.state_receiver_contract_address_, lhs_arena,
      &other->_impl_.state_receiver_contract_address_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata BorEventsReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_remote_2fbor_2eproto_getter, &descriptor_table_remote_2fbor_2eproto_once,
      file_level_metadata_remote_2fbor_2eproto[3]);
}

// ===================================================================

class BorProducersRequest::_Internal {
 public:
};

BorProducersRequest::BorProducersRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.BorProducersRequest)
}
BorProducersRequest::BorProducersRequest(const BorProducersRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BorProducersRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_num_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.block_num_ = from._impl_.block_num_;
  // @@protoc_insertion_point(copy_constructor:remote.BorProducersRequest)
}

inline void BorProducersRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_num_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BorProducersRequest::~BorProducersRequest() {
  // @@protoc_insertion_point(destructor:remote.BorProducersRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BorProducersRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BorProducersRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BorProducersRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.BorProducersRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_num_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BorProducersRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 block_num = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.block_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BorProducersRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.BorProducersRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 block_num = 1;
  if (this->_internal_block_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_block_num(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.BorProducersRequest)
  return target;
}

size_t BorProducersRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.BorProducersRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 block_num = 1;
  if (this->_internal_block_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_block_num());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BorProducersRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BorProducersRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BorProducersRequest::GetClassData() const { return &_class_data_; }


void BorProducersRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BorProducersRequest*>(&to_msg);
  auto& from = static_cast<const BorProducersRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.BorProducersRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_block_num() != 0) {
    _this->_internal_set_block_num(from._internal_block_num());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BorProducersRequest::CopyFrom(const BorProducersRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.BorProducersRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BorProducersRequest::IsInitialized() const {
  return true;
}

void BorProducersRequest::InternalSwap(BorProducersRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.block_num_, other->_impl_.block_num_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BorProducersRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_remote_2fbor_2eproto_getter, &descriptor_table_remote_2fbor_2eproto_once,
      file_level_metadata_remote_2fbor_2eproto[4]);
}

// ===================================================================

class BorProducersResponse::_Internal {
 public:
  static const ::remote::Validator& proposer(const BorProducersResponse* msg);
};

const ::remote::Validator&
BorProducersResponse::_Internal::proposer(const BorProducersResponse* msg) {
  return *msg->_impl_.proposer_;
}
BorProducersResponse::BorProducersResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.BorProducersResponse)
}
BorProducersResponse::BorProducersResponse(const BorProducersResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BorProducersResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.validators_){from._impl_.validators_}
    , decltype(_impl_.proposer_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_proposer()) {
    _this->_impl_.proposer_ = new ::remote::Validator(*from._impl_.proposer_);
  }
  // @@protoc_insertion_point(copy_constructor:remote.BorProducersResponse)
}

inline void BorProducersResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.validators_){arena}
    , decltype(_impl_.proposer_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BorProducersResponse::~BorProducersResponse() {
  // @@protoc_insertion_point(destructor:remote.BorProducersResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BorProducersResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.validators_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.proposer_;
}

void BorProducersResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BorProducersResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.BorProducersResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.validators_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.proposer_ != nullptr) {
    delete _impl_.proposer_;
  }
  _impl_.proposer_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BorProducersResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .remote.Validator proposer = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_proposer(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .remote.Validator validators = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_validators(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BorProducersResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.BorProducersResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .remote.Validator proposer = 1;
  if (this->_internal_has_proposer()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::proposer(this),
        _Internal::proposer(this).GetCachedSize(), target, stream);
  }

  // repeated .remote.Validator validators = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_validators_size()); i < n; i++) {
    const auto& repfield = this->_internal_validators(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.BorProducersResponse)
  return target;
}

size_t BorProducersResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.BorProducersResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .remote.Validator validators = 2;
  total_size += 1UL * this->_internal_validators_size();
  for (const auto& msg : this->_impl_.validators_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .remote.Validator proposer = 1;
  if (this->_internal_has_proposer()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.proposer_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BorProducersResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BorProducersResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BorProducersResponse::GetClassData() const { return &_class_data_; }


void BorProducersResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BorProducersResponse*>(&to_msg);
  auto& from = static_cast<const BorProducersResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.BorProducersResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.validators_.MergeFrom(from._impl_.validators_);
  if (from._internal_has_proposer()) {
    _this->_internal_mutable_proposer()->::remote::Validator::MergeFrom(
        from._internal_proposer());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BorProducersResponse::CopyFrom(const BorProducersResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.BorProducersResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BorProducersResponse::IsInitialized() const {
  return true;
}

void BorProducersResponse::InternalSwap(BorProducersResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.validators_.InternalSwap(&other->_impl_.validators_);
  swap(_impl_.proposer_, other->_impl_.proposer_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BorProducersResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_remote_2fbor_2eproto_getter, &descriptor_table_remote_2fbor_2eproto_once,
      file_level_metadata_remote_2fbor_2eproto[5]);
}

// ===================================================================

class Validator::_Internal {
 public:
  static const ::types::H160& address(const Validator* msg);
};

const ::types::H160&
Validator::_Internal::address(const Validator* msg) {
  return *msg->_impl_.address_;
}
void Validator::clear_address() {
  if (GetArenaForAllocation() == nullptr && _impl_.address_ != nullptr) {
    delete _impl_.address_;
  }
  _impl_.address_ = nullptr;
}
Validator::Validator(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.Validator)
}
Validator::Validator(const Validator& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Validator* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.address_){nullptr}
    , decltype(_impl_.id_){}
    , decltype(_impl_.voting_power_){}
    , decltype(_impl_.proposer_priority_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_address()) {
    _this->_impl_.address_ = new ::types::H160(*from._impl_.address_);
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.proposer_priority_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.proposer_priority_));
  // @@protoc_insertion_point(copy_constructor:remote.Validator)
}

inline void Validator::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.address_){nullptr}
    , decltype(_impl_.id_){uint64_t{0u}}
    , decltype(_impl_.voting_power_){int64_t{0}}
    , decltype(_impl_.proposer_priority_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Validator::~Validator() {
  // @@protoc_insertion_point(destructor:remote.Validator)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Validator::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.address_;
}

void Validator::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Validator::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.Validator)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.address_ != nullptr) {
    delete _impl_.address_;
  }
  _impl_.address_ = nullptr;
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.proposer_priority_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.proposer_priority_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Validator::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .types.H160 address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_address(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 voting_power = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.voting_power_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 proposer_priority = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.proposer_priority_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Validator::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.Validator)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // .types.H160 address = 2;
  if (this->_internal_has_address()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::address(this),
        _Internal::address(this).GetCachedSize(), target, stream);
  }

  // int64 voting_power = 3;
  if (this->_internal_voting_power() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_voting_power(), target);
  }

  // int64 proposer_priority = 4;
  if (this->_internal_proposer_priority() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_proposer_priority(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.Validator)
  return target;
}

size_t Validator::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.Validator)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .types.H160 address = 2;
  if (this->_internal_has_address()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.address_);
  }

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_id());
  }

  // int64 voting_power = 3;
  if (this->_internal_voting_power() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_voting_power());
  }

  // int64 proposer_priority = 4;
  if (this->_internal_proposer_priority() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_proposer_priority());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Validator::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Validator::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Validator::GetClassData() const { return &_class_data_; }


void Validator::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Validator*>(&to_msg);
  auto& from = static_cast<const Validator&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.Validator)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_address()) {
    _this->_internal_mutable_address()->::types::H160::MergeFrom(
        from._internal_address());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_voting_power() != 0) {
    _this->_internal_set_voting_power(from._internal_voting_power());
  }
  if (from._internal_proposer_priority() != 0) {
    _this->_internal_set_proposer_priority(from._internal_proposer_priority());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Validator::CopyFrom(const Validator& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.Validator)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Validator::IsInitialized() const {
  return true;
}

void Validator::InternalSwap(Validator* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Validator, _impl_.proposer_priority_)
      + sizeof(Validator::_impl_.proposer_priority_)
      - PROTOBUF_FIELD_OFFSET(Validator, _impl_.address_)>(
          reinterpret_cast<char*>(&_impl_.address_),
          reinterpret_cast<char*>(&other->_impl_.address_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Validator::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_remote_2fbor_2eproto_getter, &descriptor_table_remote_2fbor_2eproto_once,
      file_level_metadata_remote_2fbor_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace remote
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::remote::BorTxnLookupRequest*
Arena::CreateMaybeMessage< ::remote::BorTxnLookupRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::BorTxnLookupRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::BorTxnLookupReply*
Arena::CreateMaybeMessage< ::remote::BorTxnLookupReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::BorTxnLookupReply >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::BorEventsRequest*
Arena::CreateMaybeMessage< ::remote::BorEventsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::BorEventsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::BorEventsReply*
Arena::CreateMaybeMessage< ::remote::BorEventsReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::BorEventsReply >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::BorProducersRequest*
Arena::CreateMaybeMessage< ::remote::BorProducersRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::BorProducersRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::BorProducersResponse*
Arena::CreateMaybeMessage< ::remote::BorProducersResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::BorProducersResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::Validator*
Arena::CreateMaybeMessage< ::remote::Validator >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::Validator >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
