# Reduce verbosity of CMakeDeps conan generator
# do not edit, regenerate with conan_quiet.sh

set(ZLIB_FIND_QUIETLY YES)
set(Catch2_FIND_QUIETLY YES)
set(jwt-cpp_FIND_QUIETLY YES)
set(GTest_FIND_QUIETLY YES)
set(LibtorrentRasterbar_FIND_QUIETLY YES)
set(Snappy_FIND_QUIETLY YES)
set(Microsoft.GSL_FIND_QUIETLY YES)
set(fmt_FIND_QUIETLY YES)
set(roaring_FIND_QUIETLY YES)
set(BZip2_FIND_QUIETLY YES)
set(c-ares_FIND_QUIETLY YES)
set(magic_enum_FIND_QUIETLY YES)
set(absl_FIND_QUIETLY YES)
set(OpenSSL_FIND_QUIETLY YES)
set(tomlplusplus_FIND_QUIETLY YES)
set(spdlog_FIND_QUIETLY YES)
set(SQLite3_FIND_QUIETLY YES)
set(CLI11_FIND_QUIETLY YES)
set(tl-expected_FIND_QUIETLY YES)
set(asio-grpc_FIND_QUIETLY YES)
set(benchmark_FIND_QUIETLY YES)
set(gmp_FIND_QUIETLY YES)
set(Boost_FIND_QUIETLY YES)
set(mimalloc_FIND_QUIETLY YES)
set(re2_FIND_QUIETLY YES)
set(gRPC_FIND_QUIETLY YES)
set(protobuf_FIND_QUIETLY YES)
set(Protobuf_FIND_QUIETLY YES)
set(SQLiteCpp_FIND_QUIETLY YES)
set(nlohmann_json_FIND_QUIETLY YES)
set(libdeflate_FIND_QUIETLY YES)
