name: macOS

on:
  push:
    branches:
      - master
      - 'ci/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  osx:
    runs-on: macos-latest

    # Disable on external PRs
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    strategy:
      matrix:
        config:
          - {build_type: "Release"}
      fail-fast: false # This makes it so that if 1 of the tests in the matrix fail, they don't all fail

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: "0"

    - name: Install Prerequisites
      run: |
        pip3 install --user --break-system-packages --no-warn-script-location conan==2.10.2 chardet
        conan_path="$(python3 -m site --user-base)/bin"
        echo "$conan_path" >> $GITHUB_PATH
        "$conan_path/conan" --version

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.config.cc }}-${{ matrix.config.build_type }}  # Eg. "linux_x64-ubuntu-latest-clang-12-Debug"

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      env:
        CC: ${{ matrix.config.cc}}
        CXX: ${{ matrix.config.cxx}}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config ${{ matrix.config.build_type }} -j 2

    - name: Smoke tests
      run: make "SILKWORM_BUILD_DIR=${{runner.workspace}}/build" run_smoke_tests

    - name: Unit tests
      run: make "SILKWORM_BUILD_DIR=${{runner.workspace}}/build" run_unit_tests

    - name: Ethereum EL tests
      working-directory: ${{runner.workspace}}/build
      run: |
        cmd/test/ethereum --threads 4
